name    'credativ/ssh'
version '1.0.2'
source 'https://github.com/credativ/puppet-ssh-hiera'
author 'Patrick Schoenfeld <patrick.schoenfeld@credativ.de>'
license 'MIT'
summary 'puppet module to manage ssh with a hiera backend'
description 'This module allows managing a ssh-server, including users and groups, with hiera as data backend'
project_page 'https://github.com/credativ/puppet-ssh-hiera'

dependency 'credativ/example42lib', '2.x'
